[tool.poetry]
name = "yendoria"
version = "0.1.0"
description = "A traditional tile-based roguelike built with Python and libtcod."
authors = ["Joseph Wagner <j.wagner1024@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/josephbwagner/yendoria"
repository = "https://github.com/josephbwagner/yendoria"
keywords = ["roguelike", "game", "python", "libtcod"]
packages = [{include = "yendoria", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
tcod = "^16.0.0"
numpy = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.0"
sphinx = "^7.0"
sphinx-autodoc-typehints = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
